name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

# 1. Definição do SDK do Dart (necessário)
environment:
  sdk: ^3.0.0

# 2. Dependências do aplicativo
dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.6.0
  cupertino_icons: ^1.0.8

# 3. Dependências de desenvolvimento e testes
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true