name: estacionei
description: "Plataforma de aluguel de vagas em condomínios e estacionamentos."
publish_to: 'none'
version: 1.0.0+1

# 1. Definição do SDK do Dart (necessário)
environment:
  sdk: ^3.0.0

# 2. Dependências do aplicativo
dependencies:
  flutter:
  uses-material-design: true
    sdk: flutter

  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.0
  cupertino_icons: ^1.0.8
  http: ^1.2.0

# 3. Dependências de desenvolvimento e testes
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

assets:
    - assets/images/